name: Generate Datas

on:
  schedule: # uruchamiaj co 12 godzin
    - cron: "0 */12 * * *"
  workflow_dispatch: # pozwala na ręczne uruchomienie

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    # KROK 1: Dodanie uprawnień do zapisu dla GITHUB_TOKEN
    permissions:
      contents: write

    steps:
      # Krok 2: Aktualizacja akcji do nowszych wersji
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
