name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Krok 1: Generowanie animacji węża
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jakubm3
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Krok 2: Wdrożenie do gałęzi 'output'
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          # Poprawne wcięcie dla 'env'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
